# ─────────────────────────────────────────────────────────────────────────────
# Jenkins Configuration as Code (JCasC)
# Repo: jenkins-ocp4  (separate from ocp4-upi-powervm terraform repo)
#
# Required environment variables at container startup:
#   See README.md § Environment variables
# ─────────────────────────────────────────────────────────────────────────────

jenkins:
  systemMessage: |
    OCP4 UPI PowerVM – Cluster Automation (jenkins-ocp4)
    Managed by JCasC. Edit casc/casc.yaml — not the Jenkins UI.

  # ── Controller runs jobs directly (same-machine setup) ─────────────────────
  # Jenkins creates a numbered workspace dir per concurrent build:
  #   /var/jenkins_home/workspace/cluster-create/       ← build A
  #   /var/jenkins_home/workspace/cluster-create@2/     ← build B (same job, concurrent)
  # .terraform/, data/, and plan files are fully isolated between builds.
  numExecutors: 10
  mode: NORMAL
  labelString: "terraform built-in"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID}"
          name: "Admin"
          password: "${JENKINS_ADMIN_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  # ── Global non-secret environment variables ─────────────────────────────────
  globalNodeProperties:
    - envVars:
        env:
          # URL of the JENKINS repo (this repo) — used by seed.groovy
          - key: "JENKINS_REPO_URL"
            value: "${JENKINS_REPO_URL}"
          - key: "JENKINS_REPO_BRANCH"
            value: "${JENKINS_REPO_BRANCH}"

          # URL of the TERRAFORM repo (ocp4-upi-powervm) — used by pipelines
          - key: "TF_REPO_URL"
            value: "${TF_REPO_URL}"
          - key: "TF_REPO_BRANCH"
            value: "${TF_REPO_BRANCH}"


# ─────────────────────────────────────────────────────────────────────────────
# Credentials
# ─────────────────────────────────────────────────────────────────────────────
credentials:
  system:
    domainCredentials:
      - credentials:

          # ── Terraform backend config ───────────────────────────────────────
          # Base64-encoded HCL with the local backend path.
          # See jenkins-ocp4/backend/local-persistent.hcl.example
          # Encode: printf 'path = "/opt/terraform_states/terraform.tfstate"\n' | base64
          # Stored as a secret string (not file) — JCasC secretBytes/file handling
          # has known issues with env-var interpolation; the pipeline decodes inline.
          - string:
              scope: GLOBAL
              id: "terraform-backend-config"
              secret: "${TF_BACKEND_CONFIG_B64}"
              description: "Base64-encoded Terraform backend config (.hcl) — decoded by the pipeline before terraform init"

          # ── SSH keys for Terraform ─────────────────────────────────────────
          # Base64-encode on the CentOS host (Linux):
          #   export SSH_PRIVATE_KEY_B64=$(base64 -w0 ~/.ssh/id_rsa)
          #   export SSH_PUBLIC_KEY_B64=$(base64 -w0 ~/.ssh/id_rsa.pub)
          - file:
              scope: GLOBAL
              id: "jenkins-ssh-private-key"
              fileName: "id_rsa"
              secretBytes: "${SSH_PRIVATE_KEY_B64}"
              description: "SSH private key — written to build workspace at runtime"
          - file:
              scope: GLOBAL
              id: "jenkins-ssh-public-key"
              fileName: "id_rsa.pub"
              secretBytes: "${SSH_PUBLIC_KEY_B64}"
              description: "SSH public key — written to build workspace at runtime"

          # ── Git credentials ────────────────────────────────────────────────
          - usernamePassword:
              scope: GLOBAL
              id: "git-credentials"
              username: "${GIT_USERNAME}"
              password: "${GIT_TOKEN}"
              description: "Git personal access token for repo checkout"

# ─────────────────────────────────────────────────────────────────────────────
# Plugin settings
# ─────────────────────────────────────────────────────────────────────────────
unclassified:

  ansiColorBuildWrapper:
    globalColorMapName: "xterm"

  timestamper:
    allPipelines: true

  lockableResourcesManager:
    declaredResources:
      - name: "tf-provider-init"
        description: "Serializes first provider download when the plugin cache is cold."

# ─────────────────────────────────────────────────────────────────────────────
# Bootstrap: create the seed job
# ─────────────────────────────────────────────────────────────────────────────
jobs:
  - script: |
      pipelineJob('_seed-jobs') {
        description('Bootstrap: runs Job DSL (jenkins-ocp4/jobs/seed.groovy) to create cluster-create and cluster-destroy jobs.')
        logRotator { numToKeep(10) }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url(System.getenv('JENKINS_REPO_URL'))
                  credentials('git-credentials')
                }
                branch(System.getenv('JENKINS_REPO_BRANCH') ?: 'main')
                extensions {
                  cloneOption { shallow(true); depth(1); timeout(10); noTags(false); reference('') }
                }
              }
            }
            scriptPath('pipelines/Jenkinsfile.seed')
            lightweight(false)
          }
        }
        triggers { scm('H/30 * * * *') }
        properties {
          disableConcurrentBuilds { abortPrevious(false) }
        }
      }
